### PR TITLE
Retry qsub and qstat in case of failures

### LINKED ISSUE #405: Torque driver unable to get job status
Running Ert (cli) on the Azure cluster using the torque driver
Right after starting, a message like this is spit out for every job:```** Warning: failed to get job status for job:218 from file:/tmp/enkf-qstat-5956-365084```  
I do have write access to the `/tmp` folder, but the file is not created (regular users might have write access to that folder, but that's another issue).

The jobs actually are started and complete correctly, but Ert hangs, most likely because it's unable to detect that the jobs are completed

### PR DESCRIPTION
**Pull request by berland**
**Issue**
Resolves #405 

**Approach**
Retry qstat and qsub commands in case of (intermittent) failures.

~Based on (blocked by) #3518  and #3490~

## Pre review checklist

- [x] Added appropriate release note label
- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).

Adding labels helps the maintainers when writing release notes. This is the [list of release note labels](https://github.com/equinor/ert/labels?q=release-notes).

### CODE REVIEW

File: libres/lib/job_queue/torque_driver.cpp [hunk 1]
```diff
@@ -434,11 +435,27 @@ static int torque_driver_submit_shell_job(torque_driver_type *driver,
...
-                    driver->qsub_cmd, stringlist_get_size(remote_argv),
-                    (const char **)argv, tmp_std_file, tmp_err_file);
-                if (status != 0) {
-                    torque_debug_spawn_status_info(driver, status);
+
+                /* The qsub command might fail intermittently for acceptable reasons,
+￼                  retry a couple of times with exponential sleep.  */
+                int return_value = -1;
+                int sleep_time = 2;
+                int max_sleep_time = 2 * 2 * 2 * 2; /* max 4 attempts */
```
Comment (xjules) [inline libres/lib/job_queue/torque_driver.cpp:443]: Is this like exponentially increasing `sleep_time`? If this is required then `max_sleep_time` could be just `max_sleep_count=4`, but I guess this doesn't require additional `i++`

File: libres/lib/job_queue/torque_driver.cpp [hunk 2]
```diff
@@ -514,26 +531,49 @@ void *torque_driver_submit_job(void *__driver, const char *submit_cmd,
...
         const char **argv = (const char **)util_calloc(1, sizeof *argv);
         argv[0] = jobnr_char;
 
-        util_spawn_blocking(driver->qstat_cmd, 1, (const char **)argv, tmp_file,
-                            NULL);
+        /* The qstat command might fail intermittently for acceptable reasons,
+           retry a couple of times with exponential sleep. ERT pings qstat
+           every second for every realization, thus the initial sleep time
+           is 2 seconds. */
+        int return_value = -1;
```
Comment (xjules) [inline libres/lib/job_queue/torque_driver.cpp:548]: I guess this `return_value` parameter can go directly into the while loop; ie. `int return_value = util_spawn_blocking(...)`

**Review by xjules — COMMENTED** [review]
Just had some minor comments, but looks good nonetheless!

**Comment by jondequinor** [comment]
There's a wrapper script provided by someone located in `/prog/util/lib/pbswrap/`. It does not do exponential backoff, but it will retry 5 times. Other than that, it's pretty bare bones, and I much prefer to call `qsub/qstat` directly. My vote is on keep working on this PR.

File: libres/lib/job_queue/torque_driver.cpp (hunk 1 above)
Comment (berland) [reply libres/lib/job_queue/torque_driver.cpp]: The exponentiality is covered by `sleep_time *= 2`. Testing `sleep_time < max_sleep_time` made the while-statement nicer as far as I remember, instead of having something like `max_sleep_count = 4`.

File: libres/lib/job_queue/torque_driver.cpp (hunk 2 above)
Comment (berland) [reply libres/lib/job_queue/torque_driver.cpp]: It is needed to bootstrap the `while`-statement.

File: tests/libres_tests/res/job_queue/test_job_queue_manager.py [hunk 3]
```diff
@@ -97,6 +96,24 @@ def create_local_queue(
     return job_queue
 
 
+def create_job_queue_node(job_id=0, num_cpus=1):
```
[the remark this answers is not in the document]
Comment (berland) [reply tests/libres_tests/res/job_queue/test_job_queue_manager.py:99]: Fixed!
