### PR TITLE
Make default ensemble path consistent

### LINKED ISSUE #3925: Inconsistent  behavior when setting  ENSPATH in a config file versus not setting it
The following test should **SUCCEED** but it **FAILS** 

``` python
def test_default_resconfig_ens_path(tmpdir):
    from ert._c_wrappers.enkf import ResConfig

    with tmpdir.as_cwd():
        config_file = "test.ert"
        with open(config_file, "w") as f:
            f.write("""
NUM_REALIZATIONS  1
            """)
        res_config = ResConfig(config_file)
        # By default, the ensemble path is set to 'storage'
        default_ens_path = res_config.model_config.getEnspath()

        with open(config_file, "a") as f:
            f.write("""
ENSPATH storage            
            """)

        # Once we set the ENSPATH in the config file the behaviour
        # of getEnspath changes, it should not!
        res_config = ResConfig(config_file)
        ens_path = res_config.model_config.getEnspath()

        assert default_ens_path == ens_path
```

### PR DESCRIPTION
**Pull request by DanSava**
**Issue**
Resolves #3925

**Approach**
Get the same ensemble path if the user adds `storage` as the ENSPATH in the config file or not.

## Pre review checklist

- [x] Added appropriate release note label
- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).

Adding labels helps the maintainers when writing release notes. This is the [list of release note labels](https://github.com/equinor/ert/labels?q=release-notes).

### CODE REVIEW

File: src/clib/lib/enkf/model_config.cpp [hunk 1]
```diff
@@ -444,6 +446,9 @@ void model_config_init(model_config_type *model_config,
         model_config_set_enspath(
             model_config,
             config_content_get_value_as_abspath(config, ENSPATH_KEY));
+    else
+        model_config_set_enspath(model_config,
+                                 fs::absolute(DEFAULT_ENSPATH).c_str());
```
Comment (valentin-krasontovitsch) [inline src/clib/lib/enkf/model_config.cpp:451]: doesn't it make more sense to add the `fs::absolute` in line 262, in `model_config_alloc_empty`? that seems to be where the inconsitent value `storage` is written.

**Review by valentin-krasontovitsch — CHANGES_REQUESTED** [review]
LGTM besides the location of adding the absolute path

File: src/clib/lib/enkf/model_config.cpp (hunk 1 above)
Comment (DanSava) [reply src/clib/lib/enkf/model_config.cpp:451]: Good point, initial solution required access to the `config_content` object until I realized I don't really need it :)

**Review by valentin-krasontovitsch — APPROVED** [review]

**Comment by valentin-krasontovitsch** [comment]
:ship: :it:
