### PR TITLE
Fix bug where duplicate dates in summary caused update to crash

### LINKED ISSUE #5967: Check how ert behaves when there are duplicate dates in summary files
There is a potential bug when we are merging datasets where there are duplicate dates in the summary response.

### PR DESCRIPTION
**Pull request by oyvindeide**
We drop all duplicate time steps from the summary dates, and only read the first one.

**Issue**
Resolves #5967

**Approach**
_Short description of the approach_

## Pre review checklist

- [ ] Read through the code changes carefully after finishing work
- [ ] Make sure tests pass locally (after every commit!)
- [ ] Wait for tests in CI to pass (see "checks" below)
- [ ] Prepare changes in small commits for more convenient review (optional)
- [ ] PR title captures the intent of the changes, and is fitting for release notes.
- [ ] Updated documentation
- [ ] Ensured new behaviour is tested (opened GUI? screenshots? tried workflows?)
- [ ] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).

## Pre merge checklist
- [ ] Added appropriate release note label
- [ ] Commit history is consistent and clean, in line with the [contribution
  guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by dafeda — APPROVED** [review]
Seems reasonable 👍

File: src/clib/lib/enkf/read_summary.cpp [hunk 1]
```diff
@@ -23,12 +23,15 @@ ERT_CLIB_SUBMODULE("_read_summary", m) {
               const ecl_smspec_type *smspec = ecl_sum_get_smspec(summary);
               std::vector<std::pair<std::string, std::vector<double>>>
                   summary_vectors{};
-
+              std::vector<std::string> seen_keys{};
```
Comment (eivindjahren) [inline src/clib/lib/enkf/read_summary.cpp:26]: I believe it should be simpler to use `std::set`

**Review by eivindjahren — APPROVED** [review]
:+1:
