### PR TITLE
Make sure loading gui produces just one storage folder

### LINKED ISSUE #4054: Loading gui produces two `storage` folders
**Describe the bug**

**To reproduce**
Steps to reproduce the behaviour:
1. Stand in `ert` root folder.
2. Load gui by running `ert gui test-data/poly_example/poly.ert`
3. Close gui
4. This is created:
logs/
storage/
test-data/poly_example/storage/

**Expected behaviour**
I expect a single `storage` folder.

**Environment**
 - OS: macOS Monteray
 - ERT main
 - Python version 3.8
 - Remote/HPC execution involved: no

### PR DESCRIPTION
**Pull request by dafeda**
**Issue**
Resolves #4054

## Pre review checklist

- [x] Added appropriate release note label
- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).

Adding labels helps the maintainers when writing release notes. This is the [list of release note labels](https://github.com/equinor/ert/labels?q=release-notes).

### CODE REVIEW

File: src/clib/lib/enkf/model_config.cpp [hunk 1]
```diff
@@ -239,8 +239,7 @@ model_config_type *model_config_alloc_empty() {
     model_config->num_realizations = 0;
     model_config->obs_config_file = NULL;
 
-    model_config_set_enspath(model_config,
-                             fs::absolute(DEFAULT_ENSPATH).c_str());
+    model_config_set_enspath(model_config, DEFAULT_ENSPATH);
```
Comment (DanSava) [inline src/clib/lib/enkf/model_config.cpp:242]: This will probably cause the test `test_default_model_config_ens_path` to fail. 

So as a quick fix I would suggest also replacing 
```python
    if (config_content_has_item(config, ENSPATH_KEY))
        model_config_set_enspath(
            model_config,
            config_content_get_value_as_abspath(config, ENSPATH_KEY));
```
with 
``` python 
    if (config_content_has_item(config, ENSPATH_KEY))
        model_config_set_enspath(
            model_config,
            config_content_get_value_as_abspath(config, ENSPATH_KEY));
    else
        model_config_set_enspath(
            model_config,
            config_content_get_value_as_abspath(config, DEFAULT_RUNPATH));
```
I know this makes `model_config_set_enspath(model_config, DEFAULT_ENSPATH);` on ln 242 (what a nice palindromic number) a bit useless but it might be ok to just remove that line altogether

Comment (DanSava) [reply src/clib/lib/enkf/model_config.cpp:242]: also `namespace fs = std::filesystem;` can be removed also

Comment (dafeda) [reply src/clib/lib/enkf/model_config.cpp:242]: What if we instead fix the test to assert that `assert default_ens_path == set_in_file_ens_path` but where we add `res_config.config_path` to `default_ens_path`?

Comment (DanSava) [reply src/clib/lib/enkf/model_config.cpp:242]: I am not sure the test needs a fix. Are you suggesting fixing `getEnspath` from `ModelConfig` to make sure it contains `res_config.config_path` ?

Comment (DanSava) [reply src/clib/lib/enkf/model_config.cpp:242]: **Fixed** :arrow_up:  replaced `config_content_get_value_as_abspath(config, DEFAULT_RUNPATH));` with `config_content_get_value_as_abspath(config, DEFAULT_ENSPATH));`

**Review by DanSava — APPROVED** [review]
:+1:
