### PR TITLE
Fix instances of ConfigValidationError exception where config file is reported as None

### LINKED ISSUE #4842: Analysis module not found message says "Error(s) in configuration file:None"

### PR DESCRIPTION
**Pull request by DanSava**
**Issue**
Resolves #4842

## Pre review checklist

- [ ] Added appropriate release note label
- [ ] PR title captures the intent of the changes, and is fitting for release notes.
- [ ] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [ ] Updated documentation
- [ ] Ensured new behaviour is tested

Adding labels helps the maintainers when writing release notes. This is the [list of release note labels](https://github.com/equinor/ert/labels?q=release-notes).

### CODE REVIEW

**Comment by oysteoh** [comment]
Is it possible to also alter the message slightly when fixing this? It is describing perfectly fine what is wrong, but i would like it to be more clear that `observations` is a file or folder - does that make sense? 
Instead of  
`Error(s) in configuration file poly.ert: ['Cannot find file or directory observations in /datadisk/repos/ert/test-data/poly_example ']` 

i.e
`Error(s) in configuration file poly.ert: ['Cannot find file or directory "observations" in path "/datadisk/repos/ert/test-data/poly_example"']` 


This is just nitpicking of course....

**Comment by DanSava** [comment]
> Is it possible to also alter the message slightly when fixing this? It is describing perfectly fine what is wrong, but i would like it to be more clear that `observations` is a file or folder - does that make sense? Instead of `Error(s) in configuration file poly.ert: ['Cannot find file or directory observations in /datadisk/repos/ert/test-data/poly_example ']`

How do I reproduce this error :arrow_up:?

File: src/clib/lib/config/config_schema_item.cpp [hunk 1]
```diff
@@ -388,8 +388,8 @@ bool config_schema_item_validate_set(const config_schema_item_type *item,
                     char *path = config_path_elm_alloc_abspath(path_elm, value);
                     if (!util_entry_exists(path)) {
                         error_list.push_back(util_alloc_sprintf(
-                            "Cannot find file or directory %s in %s ", value,
-                            config_path_elm_get_abspath(path_elm)));
+                            "Cannot find file or directory %s in path %s ",
```
Comment (oysteoh) [inline src/clib/lib/config/config_schema_item.cpp:391]: Only one more small comment as it seems you missed that part in my previous comment - i would also like to distinguish the file/dirname from the sentence as currently it becomes like this ( running the poly.ert and remove the observation file )
`Cannot find file or directory observations ... `

it would be much more clear that the file/dir defined wrong/not exists if the sentence is something like this
`Cannot find file or directory "observations" ... `
or 
`Cannot find file or directory <observations> ... `
or something else which makes sense.... Not sure if this is necessary - but i just feel that it is a bit more informative

**Review by oysteoh — APPROVED** [review]

**Review by andreas-el — APPROVED** [review]
:+1:
