### PR TITLE
Cover previously unhandled job queue state `JOB_QUEUE_DO_KILL_NODE_FAILURE`

### LINKED ISSUE #4809: Assertion Error of unexpected job status can happen with JOB_QUEUE_DO_KILL_NODE_FAILURE
https://github.com/equinor/ert/blob/b828844409c74bcd22bd57f7196c9861a4bb8694/src/ert/_c_wrappers/job_queue/job_queue_node.py#L249-L252

### PR DESCRIPTION
**Pull request by valentin-krasontovitsch**
**Issue**
Possibly resolved #4809 

**Approach**
- increase timeout before job considered unconfirmed beyond recovery
- handle unconfirmed state gracefully

## Pre review checklist

- [X] Added appropriate release note label
- [X] PR title captures the intent of the changes, and is fitting for release notes.
- [X] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [ ] IRRELEVANT - Updated documentation
- [ ] GOING TO, USING USERS - Ensured new behaviour is tested

Adding labels helps the maintainers when writing release notes. This is the [list of release note labels](https://github.com/equinor/ert/labels?q=release-notes).

### CODE REVIEW

File: src/clib/lib/job_queue/job_node.cpp [hunk 1]
```diff
@@ -281,7 +281,7 @@ job_queue_node_alloc(const char *job_name, const char *run_path,
     node->sim_start = 0;
     node->sim_end = 0;
     node->submit_time = time(NULL);
-    node->max_confirm_wait = 60 * 2; // 2 minutes before we consider job dead.
+    node->max_confirm_wait = 60 * 10; // 2 minutes before we consider job dead.
```
Comment (oysteoh) [inline src/clib/lib/job_queue/job_node.cpp:284]: comment still valid after this change?

Comment (valentin-krasontovitsch) [reply src/clib/lib/job_queue/job_node.cpp:284]: haha lol obviously not XD sorry, and thanks for catching that ^^

Comment (valentin-krasontovitsch) [reply src/clib/lib/job_queue/job_node.cpp]: fixed!

**Review by berland — APPROVED** [review]
Looks good to go, remember to squash the fixup commit
