### PR TITLE
Let torque driver pick up error codes from jobs

### LINKED ISSUE #3726: Torque driver does not handle non-zero exit code from jobs
**Describe the bug**
The torque driver does not propagate information about failing jobs in the same way as the other drivers. For example, the LSF driver will return `JOB_QUEUE_EXIT` if the LSF job exited with non-zero exit code. The torque driver can produce the following statuses (see also http://docs.adaptivecomputing.com/torque/4-1-3/Content/topics/commands/qstat.htm#standardOutput):

https://github.com/equinor/ert/blob/94a29ddf18ec6f72e94d5cbc6a097c57db67a411/src/libres/lib/job_queue/torque_driver.cpp#L609-L631

This will lead to strange behavior, where ERT will attempt to load data, even though the job failed. The realization will be marked as successful, despite having failed jobs. 

**To reproduce**
Can be reproduced by adding a failing job after the `pole_eval` in the poly example, and using the torque driver. 
Data will be loaded and the realization appear successful, even though the last job failed. 

**Expected behaviour**
Handle failing jobs the same way as e.g. the LSF driver does, where jobs exiting with non-zero error code will propagate `JOB_QUEUE_EXIT` from the driver and not `JOB_QUEUE_DONE`

**Screenshots**
image

**Environment**
 - OS: RHEL7
 - ERT/Komodo release: bleeding (~2.38) on azure
 - Python version: 3.8
 - Remote/HPC execution involved: yes

**Additional context**
N/A

See also: https://github.com/equinor/ert/issues/3781

### PR DESCRIPTION
**Pull request by berland**
**Issue**
Resolves #3726 

**Approach**
Add `-f` as a hard-coded option supplied to the `qstat` command. This changes the output format from qstat from one-line pr. job to multiple lines pr. job. Only then is the exit code from the cluster made available to the torque driver.

## Pre review checklist

- [x] Added appropriate release note label
- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).

Adding labels helps the maintainers when writing release notes. This is the [list of release note labels](https://github.com/equinor/ert/labels?q=release-notes).

### CODE REVIEW

**Comment by hnformentin** [comment]
Nice PR. Could you please take a look on why some tests are not passing? Flakiness?

File: src/clib/lib/job_queue/torque_driver.cpp [hunk 1]
```diff
@@ -530,9 +534,11 @@ torque_driver_get_qstat_status(torque_driver_type *driver,
     job_status_type status = JOB_QUEUE_STATUS_FAILURE;
 
     {
-        const char **argv = (const char **)util_calloc(2, sizeof *argv);
-        argv[0] = driver->qstat_opts;
-        argv[1] = jobnr_char;
+        char const *hard_coded_qstat_option = "-f";
+        const char **argv = (const char **)util_calloc(3, sizeof *argv);
```
Comment (pinkwah) [inline src/clib/lib/job_queue/torque_driver.cpp:538]: Nitpicks (I realise this isn't new code but still)

Allocate `argv` on the stack.
```suggestion
        const char *argv[3];
```

Alternatively, using fancy C++: (add `#include <vector>` at the top if it doesn't exist)
```c++
    std::vector<const char *> argv{
        hard_coded_qstat_option,
        driver->qstat_opts,
        jobnr_char,
    };
```

Then:
* Remove `free(argv);` on line 562.
* Use `argv.size()` instead of the literal `3`.
* Use `argv.data()` instead of `(const char **)argv` (the cast is unnecessary anyway; the type is already `const char **`)

You can also replace `std::vector` with `std::array` to be invited to the secret cult of C++11. (The difference is marginal and `std::array` is likely slightly harder to use, but would be the most "efficient" thing to do in this case)

File: src/clib/lib/job_queue/torque_driver.cpp [hunk 2]
```diff
@@ -575,74 +581,91 @@ job_status_type torque_driver_parse_status(const char *qstat_file,
...
-                    }
+    /* Parse the qstat output, looking only for requested job_id */
+    if (fs::exists(qstat_file)) {
+
+        std::string job_id_label("Job Id: ");
+        int pos;
+        int job_id = -1;
+        std::string job_state("_void_");
+        int exit_status = 0;
+        std::ifstream qstatoutput(qstat_file);
```
Comment (pinkwah) [inline src/clib/lib/job_queue/torque_driver.cpp:604]: These days I like to add:
```
qstatoutput.exceptions(qstatoutput.failbit);
```

This will throw a C++ exception if the file doesn't exist (it'll check and potentially fail as soon as you call `.exceptions(`), if you try to read a formatted value that isn't correct (ie, if the buffer doesn't contain a number and you try to read a number, throw exception). Notably, if you get EOF it doesn't throw (until you try to read again I think).

Handle errors with
```c++
try {
    int number;
    qstatoutput >> number;
} catch (std::ios::failure &) {
    // do something else
}
```

*Also*:
Use `qstatoutput.imbue(std::locale::classic());`. This will set C locale to this stream object and will help us avoid the `,` vs `.` problems that we currently have.

See: https://en.cppreference.com/w/cpp/io/basic_ios/fail

File: src/clib/lib/job_queue/torque_driver.cpp (hunk 1 above)
Comment (berland) [reply src/clib/lib/job_queue/torque_driver.cpp]: Thanks, all nitpicks implemented!

**Comment by berland** [comment]
> Nice PR. Could you please take a look on why some tests are not passing? Flakiness?

Tests passing now!

File: src/clib/lib/job_queue/torque_driver.cpp [hunk 3]
```diff
@@ -530,9 +535,9 @@ torque_driver_get_qstat_status(torque_driver_type *driver,
     job_status_type status = JOB_QUEUE_STATUS_FAILURE;
 
     {
-        const char **argv = (const char **)util_calloc(2, sizeof *argv);
-        argv[0] = driver->qstat_opts;
-        argv[1] = jobnr_char;
+        char const *hard_coded_qstat_option = "-f";
```
Comment (xjules) [inline src/clib/lib/job_queue/torque_driver.cpp:538]: Can this variable name be more explicit? ex. `full_output_option`?

Comment (berland) [reply src/clib/lib/job_queue/torque_driver.cpp:538]: I think it is valuable to tag it in the code that this is an option that the driver hard-codes. But a comment explaining what `-f` means is absolutely warranted!

Comment (berland) [reply src/clib/lib/job_queue/torque_driver.cpp:538]: Comment added.

**Comment by berland** [comment]
Squashed commits.

**Review by xjules — APPROVED** [review]
Good job! 🚀
