### PR TITLE
Raise meaningful exception when accessing non existing analysis module

### LINKED ISSUE #2714: Using ANALYSIS_SET_VAR with unknown analysis module gives cryptic error message
**Describe the bug**

**To Reproduce**
1. Edit the poly case config by adding:
`ANALYSIS_SET_VAR  UNKNOWN  UNKNOWN  0.97`
2. Run the poly case.

**Expected behavior**
Would expect a good error message telling me that the analysis module is not recognised. Instead I get:
`libc++abi: terminating with uncaught exception of type std::out_of_range: unordered_map::at: key not found`

As a side not, the documentation says `IES` should be recognised, yet it is not.

### PR DESCRIPTION
**Pull request by ManInFez**
**Issue**
Resolves #2714 

**Approach**
Raise exception when accessing analysis modules which does not exist

## Pre review checklist

- [x] Added appropriate labels

Adding labels helps the maintainers when writing release notes, see sections and the
corresponding labels here: https://github.com/equinor/ert/blob/main/.github/release.yml

### CODE REVIEW

File: libres/lib/enkf/analysis_config.cpp [hunk 1]
```diff
@@ -252,7 +252,14 @@ void analysis_config_add_module_copy(analysis_config_type *config,
...
 analysis_config_get_module(const analysis_config_type *config,
                            const char *module_name) {
-    return config->analysis_modules.at(module_name);
+    if (analysis_config_has_module(config, module_name)) {
+        return config->analysis_modules.at(module_name);
+    } else {
+        char buffer[50];
+        sprintf(buffer, "Internal error - Analisys module named %s not found",
+                module_name);
+        throw std::invalid_argument(buffer);
```
Comment (pinkwah) [inline libres/lib/enkf/analysis_config.cpp:261]: If you `#include <fmt/format.h>` you can do:

```suggestion
        throw std::invalid_argument(fmt::format("Analysis module named {} not found", module_name));
```

As it stands currently, this code is susceptible to buffer overflow.

Comment (ManInFez) [reply libres/lib/enkf/analysis_config.cpp:261]: nice!

**Comment by oyvindeide** [comment]
Looks good to me, did you look into how much work it is to catch the exception when the config is loaded? If I have an error in the config now I get a meaningfull error, but still get an error, and does not exit gracefully.

**Comment by ManInFez** [comment]
> Looks good to me, did you look into how much work it is to catch the exception when the config is loaded? If I have an error in the config now I get a meaningfull error, but still get an error, and does not exit gracefully.

I am not sure how graceful it is, but one util_abort coming up :)

**Comment by oyvindeide** [comment]
> > 
> 
> I am not sure how graceful it is, but one util_abort coming up :)

Yeah, you might not have that much choice. Is it possible to put it even higher up the call stack, or does that not make sense?

**Comment by joakim-hove** [comment]
This whole concept og choosing module is on the way out ....

**Review by oyvindeide — APPROVED** [review]
> This whole concept og choosing module is on the way out ....

That is true, and if we delete this in a month that would be fine with me. As the code sits though I think this does add some value in terms of validation.
