### PR TITLE
Verify that refcase is found for history observations

### LINKED ISSUE #4758: Segfault when no HISTORY_SOURCE and no REFCASE
Reproducible qith the snake_oil test-data, just remove the aforementioned keywords.
```
(testenv) andrli@be-lx919901 ~/project/ert (main)$ git diff
diff --git a/test-data/snake_oil/snake_oil.ert b/test-data/snake_oil/snake_oil.ert
index 3a36f1b..1f8f0eb 100644
--- a/test-data/snake_oil/snake_oil.ert
+++ b/test-data/snake_oil/snake_oil.ert
@@ -13,8 +13,8 @@ ENSPATH <STORAGE>/ensemble
 ECLBASE SNAKE_OIL_FIELD
 SUMMARY *
 
-HISTORY_SOURCE REFCASE_HISTORY
-REFCASE refcase/SNAKE_OIL_FIELD
+--HISTORY_SOURCE REFCASE_HISTORY
+--REFCASE refcase/SNAKE_OIL_FIELD
 
 TIME_MAP refcase/time_map.txt
 OBS_CONFIG observations/observations.txt
```

No feedback when crashing:

```
(testenv) andrli@be-lx919901 ~/project/ert (main)$ export ERT_SHOW_BACKTRACE=1
(testenv) andrli@be-lx919901 ~/project/ert (main)$ ert gui test-data/snake_oil/snake_oil.ert 
** Warning: Cannot expand * due to missing refcase file. Provide refcase file or add fully expanded SUMMARY key to configuration
Segmentation fault (core dumped)
```

### PR DESCRIPTION
**Pull request by andreas-el**
**Issue**
Resolves #4758 

We need to discuss what makes sense here.
This kind of error should optimally be raised to the UI.

https://fmu-docs.equinor.com/docs/ert/reference/configuration/keywords.html#obs-config

**Approach**
_Short description of the approach_

## Pre review checklist

- [x] Added appropriate release note label
- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [ ] Updated documentation
- [x] Ensured new behaviour is tested

Adding labels helps the maintainers when writing release notes. This is the [list of release note labels](https://github.com/equinor/ert/labels?q=release-notes).

### CODE REVIEW

File: src/clib/lib/enkf/enkf_obs.cpp [hunk 1]
```diff
@@ -460,6 +460,10 @@ static void handle_history_observation(enkf_obs_type *enkf_obs,
                         "** Could not load historical data for observation:%s "
                         "- ignored\n",
                         obs_key);
+
```
Comment (oyvindeide) [inline src/clib/lib/enkf/enkf_obs.cpp:463]: Cant comment above this, but should be possible to add:     if (num_hist_obs > 0 && enkf_obs->refcase == NULL) 
```cpp
{
        stringlist_free(hist_obs_keys);
        throw exc::invalid_argument("REFCASE required for SUMMARY_OBSERVATION");
    }
```
at line 421, and catch it in `EnKFMain` and convert it to `ConfigValidationError` to make it shown up in the Suggester

Comment (oyvindeide) [reply src/clib/lib/enkf/enkf_obs.cpp:463]: Idealy we should probably initalize the observations outside `EnKFMain`, but that is outside the scope here.

Comment (andreas-el) [reply src/clib/lib/enkf/enkf_obs.cpp:469]: I've updated the code and raised a `ConfigValidationError` from python side.

File: src/clib/lib/enkf/enkf_obs.cpp [hunk 2]
```diff
@@ -419,6 +419,12 @@ static void handle_history_observation(enkf_obs_type *enkf_obs,
             enkf_conf, "HISTORY_OBSERVATION");
     int num_hist_obs = stringlist_get_size(hist_obs_keys);
 
+    if (num_hist_obs > 0 && enkf_obs->refcase == NULL) {
+        stringlist_free(hist_obs_keys);
+        throw exc::invalid_argument(
```
Comment (oyvindeide) [inline src/clib/lib/enkf/enkf_obs.cpp:424]: Looks good, but probably need to do some cleanup on the caller side as well to free `conf_instance_type`

**Review by oyvindeide — APPROVED** [review]
LGTM! Very nice!
