### PR TITLE
Resolve ERT slowdown seen in Azure

### LINKED ISSUE #6182: Investigate ert running slowly in azure
**Describe the bug**
It seemed like between release 2023.08.rc3 and rc4, something made ert taking 3x as long to even get the realization boxes showing. We have confirmed the jobs are loaded by checking qstat -fu <USERNAME>. Between those release candidates, ert was upgraded from 5.1.0-rc0 to ert 6.0.0-rc1, maybe this is related?

**To reproduce**
Steps to reproduce the behaviour:
*  Log onto Azure RGS Node
*  Copy drogon
*  Source komodo with the release you want to try
*  Run ert and wait for the boxes to appear

### PR DESCRIPTION
**Pull request by andreas-el**
**Issue**
Resolves #6182 

[Move job_queue_node_refresh_status back to cwrap](https://github.com/equinor/ert/pull/6181/commits/788555e53a984180dd3678a5507fcb5af14d393d) 
Resolves the UI slowdowns found when running ERT in Azure
The offending function was refactored to use pybind in https://github.com/equinor/ert/pull/5841
This seem to cause resource starvation, most likely  due to the
GIL (global interpreter lock) used by python
Moving the function back to cwrap alleviates this issue

## Pre review checklist

- [x] Read through the code changes carefully after finishing work
- [x] Make sure tests pass locally (after every commit!)
- [x] Prepare changes in small commits for more convenient review (optional)
- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Updated documentation
- [x] Ensured that unit tests are added for all new behavior (See 
    [Ground Rules](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#ground-rules)),
    and changes to existing code have good test coverage.

## Pre merge checklist
- [x] Added appropriate release note label
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: src/clib/lib/job_queue/job_node.cpp [hunk 1]
```diff
@@ -261,51 +258,54 @@ bool job_queue_node_kill_simple(job_queue_node_type *node,
...
-                    MAX_CONFIRMED_WAIT, node->job_name, node->submit_attempt);
-                logger->info(error_msg);
-                msg = error_msg;
-                job_status_type new_status = JOB_QUEUE_DO_KILL_NODE_FAILURE;
-                job_queue_node_set_status(node, new_status);
-            }
-        }
+job_status_type job_queue_node_refresh_status(job_queue_node_type *node,
+                                              queue_driver_type *driver) {
+    pthread_mutex_lock(&node->data_mutex);
```
Comment (xjules) [inline src/clib/lib/job_queue/job_node.cpp:270]: What about `if (!node->job_data) {` if statement?

**Review by xjules — APPROVED** [review]
Good job! Let's get it in :rocket:
