### PR TITLE
Make the egg test run on azure

### LINKED ISSUE #10160: Egg tests fail on azure runs
The egg test fails on azure because we try to run it on LSF, which does not exist. We should make sure it runs there as well by switching to the correct queue system when tests are running in azure.

### PR DESCRIPTION
**Pull request by frode-aarstad**
**Issue**
Resolves #10160 

**Approach**
_Short description of the approach_

(Screenshot of new behavior in GUI if applicable)

- [ ] PR title captures the intent of the changes, and is fitting for release notes.
- [ ] Added appropriate release note label
- [ ] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [ ] Make sure unit tests pass locally after every commit (`git rebase -i main
      --exec 'just rapid-tests'`)

## When applicable
- [ ] **When there are user facing changes**: Updated documentation
- [ ] **New behavior or changes to existing untested code**: Ensured that unit tests are added (See [Ground Rules](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#ground-rules)).
- [ ] **Large PR**: Prepare changes in small commits for more convenient review
- [ ] **Bug fix**: Add regression test for the bug
- [ ] **Bug fix**: Create Backport PR to latest release

### CODE REVIEW

File: ci/testkomodo.sh [hunk 1]
```diff
@@ -60,36 +60,42 @@ remove_one_week_old_temp_folders () {
 make_run_path () {
     case "$1" in
         "azure")
+            mkdir -p /lustre1/users/f_scout_ci/egg_tests
             mktemp -d -p /lustre1/users/f_scout_ci/egg_tests
             ;;
         *)
+            mkdir -p /scratch/oompf/egg_tests
```
Comment (yngve-sk) [inline ci/testkomodo.sh:67]: mkdir+mktemp needed for both azure and non azure? ref the issue being targeted to AZ only

File: ci/testkomodo.sh [hunk 2]
```diff
@@ -60,36 +60,42 @@ remove_one_week_old_temp_folders () {
...
-    pushd "${LSF_TMP_DIR}/egg"
-    echo "LSF_TMP_DIR: $LSF_TMP_DIR"
+    # Need to copy the egg test to a directory that is accessible by all cluster members
+    RUNNER_ROOT=$(make_run_path "$CI_RUNNER_LABEL")
+    mkdir -p "$RUNNER_ROOT"
+    RUNNER_TMP_DIR=$(mktemp -d -p "$RUNNER_ROOT")
+    cp -r "${CI_SOURCE_ROOT}/test-data/everest/egg" "$RUNNER_TMP_DIR"
+    chmod -R a+rx "$RUNNER_TMP_DIR"
+    pushd "${RUNNER_TMP_DIR}/egg"
+    echo "RUNNER_TMP_DIR: $RUNNER_TMP_DIR"
```
Comment (yngve-sk) [inline ci/testkomodo.sh:84]: Most of the change here is just the renaming of variables, only functional change as far as I can see is the chmod after copy, which I guess is intentional? Could we have the rename in a separate commit before this one?

File: ci/testkomodo.sh [hunk 3]
```diff
@@ -60,36 +60,42 @@ remove_one_week_old_temp_folders () {
...
-    # Need to activate a komodo version available on LSF. Not a komodoenv
     disable_komodo
     # shellcheck source=/dev/null
     source "${_KOMODO_ROOT}/${_FULL_RELEASE_NAME}/enable"
 
-
     CONFIG="everest/model/config.yml"
-    sed -i "s/name: local/name: lsf/g" "$CONFIG"
+    if [[ "$CI_RUNNER_LABEL" == "azure" ]]; then
+        sed -i "s/name: local/name: torque\n    queue: permanent_8/g" "$CONFIG"
```
Comment (yngve-sk) [inline ci/testkomodo.sh:92]: For torque, do we need to specify the queue name, but not for LSF?

File: src/everest/bin/everest_script.py [hunk 4]
```diff
@@ -141,7 +141,7 @@ async def run_everest(options):
         logging_level = logging.DEBUG if options.debug else options.config.logging_level
         await start_server(options.config, logging_level)
         print("Waiting for server ...")
-        wait_for_server(options.config.output_dir, timeout=600)
+        wait_for_server(options.config.output_dir, timeout=1800)  # 30 minutes
```
Comment (yngve-sk) [inline src/everest/bin/everest_script.py:144]: Was there a very long wait time for startup on torque?
Could have this change in a separate commit saying why the increase was done?

File: ci/testkomodo.sh (hunk 1 above)
Comment (frode-aarstad) [reply ci/testkomodo.sh:67]: Its nice to have if the scratch/oompf/egg_tests were deleted somehow

File: ci/testkomodo.sh (hunk 2 above)
Comment (frode-aarstad) [reply ci/testkomodo.sh:84]: Should be part of this commit

File: ci/testkomodo.sh (hunk 3 above)
Comment (frode-aarstad) [reply ci/testkomodo.sh:92]: Yes

File: ci/testkomodo.sh (hunk 2 above)
Comment (yngve-sk) [reply ci/testkomodo.sh:84]: I'm not really sure I see why the renaming shouldn't be kept separate from the behavior change? Is this change also as strictly necessary for the bugfix the same way the change below is?

Comment (frode-aarstad) [reply ci/testkomodo.sh:84]: Its not strictly a bugfix its a PR for making the egg test run on both azure and onprem. Hence the naming changes

File: src/everest/bin/everest_script.py (hunk 4 above)
Comment (berland) [reply src/everest/bin/everest_script.py]: Any extra timeout could perhaps be set in ci/testkomodo as an argument to pytest?

Comment (frode-aarstad) [reply src/everest/bin/everest_script.py]: With the change of queue from "normal" to "permanent" the original timeout should be fine for now

**Review by yngve-sk — APPROVED** [review]
