### PR TITLE
Fix ssl error

### LINKED ISSUE #9623: ssl.SSLError: Fix everest flaky tests
In komodo bleeding ert tests this error tends to popup regularly:

```sh
Traceback (most recent call last):
  File "/usr/lib64/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.11/site-packages/everest/detached/jobs/everserver.py", line 156, in _everserver_thread
    uvicorn.run(
  File "/prog/res/komodo/bleeding-20241224-0207-py311-rhel8/root/lib64/python3.11/site-packages/uvicorn/main.py", line 579, in run
    server.run()
  File "/prog/res/komodo/bleeding-20241224-0207-py311-rhel8/root/lib64/python3.11/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/prog/res/komodo/bleeding-20241224-0207-py311-rhel8/root/lib64/python3.11/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/prog/res/komodo/bleeding-20241224-0207-py311-rhel8/root/lib64/python3.11/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/prog/res/komodo/bleeding-20241224-0207-py311-rhel8/root/lib64/python3.11/site-packages/uvicorn/config.py", line 400, in load
    self.ssl: ssl.SSLContext | None = create_ssl_context(
                                      ^^^^^^^^^^^^^^^^^^^
  File "/prog/res/komodo/bleeding-20241224-0207-py311-rhel8/root/lib64/python3.11/site-packages/uvicorn/config.py", line 113, in create_ssl_context
    ctx.load_cert_chain(certfile, keyfile, get_password)
ssl.SSLError: [SSL] PEM lib (_ssl.c:3938)
```

https://github.com/equinor/komodo-releases/actions/runs/12475212781/job/34818748086

### PR DESCRIPTION
**Pull request by DanSava**
**Issue**
Resolves #9623

**Approach**
Remove test_everest_output

The test was checking that starting the Everest server will roll the Everest output folder. Which it should not do and the test was rolling the folder itself.

The test was also starting two Everest servers quickly without waiting for any of them to finish. 

- [ ] PR title captures the intent of the changes, and is fitting for release notes.
- [ ] Added appropriate release note label
- [ ] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [ ] Make sure unit tests pass locally after every commit (`git rebase -i main
      --exec 'pytest tests/ert/unit_tests tests/everest -n auto --hypothesis-profile=fast -m "not integration_test"'`)

## When applicable
- [ ] **When there are user facing changes**: Updated documentation
- [ ] **New behavior or changes to existing untested code**: Ensured that unit tests are added (See [Ground Rules](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#ground-rules)).
- [ ] **Large PR**: Prepare changes in small commits for more convenient review
- [ ] **Bug fix**: Add regression test for the bug
- [ ] **Bug fix**: Create Backport PR to latest release

### CODE REVIEW

File: ci/testkomodo.sh [hunk 1]
```diff
@@ -35,8 +35,7 @@ run_ert_with_opm() {
 }
 
 run_everest_tests() {
-    python -m pytest -n auto tests/everest -s \
-    --ignore-glob "*test_visualization_entry*"
+    python -m pytest -n auto tests/everest -s
```
Comment (frode-aarstad) [inline ci/testkomodo.sh:38]: I guess this is not relevant anymore?

**Review by frode-aarstad — APPROVED** [review]
Good job! 🚀

File: ci/testkomodo.sh (hunk 1 above)
Comment (DanSava) [reply ci/testkomodo.sh:38]: `--ignore-glob "*test_visualization_entry*"` is not needed anymore I changed the test so that it uses a mocked plugin manager so we ar no longer dependent on what is installed in the environment.
