### PR TITLE
Remove changing mode of files by ext_job

### LINKED ISSUE #1907: Stop changing the permissions of job executables
If a forward model config has the same name as the `EXECUTABLE` but different case, this will fail on case insensitive systems. Libres will change the executable bit on the config and pass it to job dispatch as an executable, leading to some strange behavior.

A couple of things could be changed:

* libres should probably not change the executable bit
* libres presumably first searches cwd for a file, before searching `PATH`, order should perhaps be reversed?

### PR DESCRIPTION
**Pull request by ManInFez**
**Issue**
Resolves #1907 

## Pre review checklist

- [x] Added appropriate labels

Adding labels helps the maintainers when writing release notes, see sections and the
corresponding labels here: https://github.com/equinor/ert/blob/main/.github/release.yml

### CODE REVIEW

**Comment by oyvindeide** [comment]
Looks like a good change 👍 Because this might cause some workflows and forward models to fail because they rely on this behavior, how does this fail if we dont have execute permission, is the error message understandable?

**Comment by ManInFez** [comment]
> Looks like a good change +1 Because this might cause some workflows and forward models to fail because they rely on this behavior, how does this fail if we dont have execute permission, is the error message understandable?

It outputs an error message saying you do not have execution rights to this file 
https://github.com/equinor/ert/blob/ac2ea6ecc0d7f8323414e0f3a46c8261f48d048b/libres/lib/job_queue/ext_job.cpp#L444

**Comment by oyvindeide** [comment]
The reason I am asking so much is I once ended up trying to debug when this happened, and was not the first thing I thought of, so took me some time to figure out.

**Comment by ManInFez** [comment]
test libres please!

File: libres/lib/job_queue/ext_job.cpp [hunk 1]
```diff
@@ -463,14 +441,13 @@ void ext_job_set_executable(ext_job_type *ext_job, const char *executable_abs,
...
             if (!util_is_executable(ext_job->executable)) {
-                fprintf(stderr,
-                        "** You do not have execute rights to:%s - job will "
-                        "not be available.\n",
-                        ext_job->executable);
-                ext_job->__valid =
-                    false; /* Mark the job as NOT successfully installed - the ext_job
-                                      instance will later be freed and discarded. */
+                throw std::invalid_argument(
+                    fmt::format("** You do not have execute rights to:{}",
```
Comment (oyvindeide) [inline libres/lib/job_queue/ext_job.cpp:445]: Missing space after :

**Review by oyvindeide — COMMENTED** [review]
Looks good, just running some checks, would it make sense to add a test to this?

File: libres/lib/job_queue/ext_job.cpp (hunk 1 above)
Comment (ManInFez) [reply libres/lib/job_queue/ext_job.cpp]: Fixed and added some test

**Comment by ManInFez** [comment]
test ert please!

**Review by oyvindeide — COMMENTED** [review]
There is now a clear warning in the console if this occurs so a great improvement 👍 It is only a warning though, and cant quite agree with myself if I think it should be an error. If you try to actually use the forward model, you will get an error, but then it is not so clear, you have to put it in context with the previous warnings, for example you get:
```
Error message: ext_joblist_get_job_copy: asked for job:MY_CUSTOM_JOB which does not exist

See file: /tmp/ert_abort_dump.log for more details of the crash.
Setting the environment variable "ERT_SHOW_BACKTRACE" will show the backtrace on stderr.
```

then the warning is higher in the console:
```
Error parsing executable: ** You do not have execute rights to: /some/path/MY_CUSTOM_JOB** Warning: job: 'MY_CUSTOM_JOB' not available ...
```

maybe it would be better to error right away?

**Comment by ManInFez** [comment]
> There is now a clear warning in the console if this occurs so a great improvement +1 It is only a warning though, and cant quite agree with myself if I think it should be an error. If you try to actually use the forward model, you will get an error, but then it is not so clear, you have to put it in context with the previous warnings, for example you get:
> 
> ```
> Error message: ext_joblist_get_job_copy: asked for job:MY_CUSTOM_JOB which does not exist
> 
> See file: /tmp/ert_abort_dump.log for more details of the crash.
> Setting the environment variable "ERT_SHOW_BACKTRACE" will show the backtrace on stderr.
> ```
> 
> then the warning is higher in the console:
> 
> ```
> Error parsing executable: ** You do not have execute rights to: /some/path/MY_CUSTOM_JOB** Warning: job: 'MY_CUSTOM_JOB' not available ...
> ```
> 
> maybe it would be better to error right away?

This will cause the python constructor to segfault when something is wrong, as it will not be able to capture the exception. I think the scope of the issue becomes a little too large for this PR.

**Comment by oyvindeide** [comment]
> This will cause the python constructor to segfault when something is wrong, as it will not be able to capture the exception. I think the scope of the issue becomes a little too large for this PR.

I know, it is not ideal, but it ends up doing that anyway when it ulimately calls `util_abort, and the message just becomes a bit less clear because it says it did not find the job. Could for catch the exceptions and accumulate them before reraising with the full message. And either not catch it at all, or recatch even higher up.

**Comment by ManInFez** [comment]
I would prefer to not change this behaviour in this PR, but I can make an issue for it?

**Review by oyvindeide — APPROVED** [review]
